//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingalrApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact1
    {
        public int ContactID { get; set; }
        public string ContactName { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    }
}
